drop table if exists iso3166_1;
create table iso3166_1 (cname varchar(255), cname_french varchar(255), alpha2 varchar(2));


insert into iso3166_1 values('AFGHANISTAN', 'AFGHANISTAN', 'AF');
insert into iso3166_1 values('ÅLAND ISLANDS', 'ÅLAND, ÎLES', 'AX');
insert into iso3166_1 values('ALBANIA', 'ALBANIE', 'AL');
insert into iso3166_1 values('ALGERIA', 'ALGÉRIE', 'DZ');
insert into iso3166_1 values('AMERICAN SAMOA', 'SAMOA AMÉRICAINES', 'AS');
insert into iso3166_1 values('ANDORRA', 'ANDORRE', 'AD');
insert into iso3166_1 values('ANGOLA', 'ANGOLA', 'AO');
insert into iso3166_1 values('ANGUILLA', 'ANGUILLA', 'AI');
insert into iso3166_1 values('ANTARCTICA', 'ANTARCTIQUE', 'AQ');
insert into iso3166_1 values('ANTIGUA AND BARBUDA', 'ANTIGUA-ET-BARBUDA', 'AG');
insert into iso3166_1 values('ARGENTINA', 'ARGENTINE', 'AR');
insert into iso3166_1 values('ARMENIA', 'ARMÉNIE', 'AM');
insert into iso3166_1 values('ARUBA', 'ARUBA', 'AW');
insert into iso3166_1 values('AUSTRALIA', 'AUSTRALIE', 'AU');
insert into iso3166_1 values('AUSTRIA', 'AUTRICHE', 'AT');
insert into iso3166_1 values('AZERBAIJAN', 'AZERBAÏDJAN', 'AZ');
insert into iso3166_1 values('BAHAMAS', 'BAHAMAS', 'BS');
insert into iso3166_1 values('BAHRAIN', 'BAHREÏN', 'BH');
insert into iso3166_1 values('BANGLADESH', 'BANGLADESH', 'BD');
insert into iso3166_1 values('BARBADOS', 'BARBADE', 'BB');
insert into iso3166_1 values('BELARUS', 'BÉLARUS', 'BY');
insert into iso3166_1 values('BELGIUM', 'BELGIQUE', 'BE');
insert into iso3166_1 values('BELIZE', 'BELIZE', 'BZ');
insert into iso3166_1 values('BENIN', 'BÉNIN', 'BJ');
insert into iso3166_1 values('BERMUDA', 'BERMUDES', 'BM');
insert into iso3166_1 values('BHUTAN', 'BHOUTAN', 'BT');
insert into iso3166_1 values('BOLIVIA, PLURINATIONAL STATE OF', 'BOLIVIE, l''ÉTAT PLURINATIONAL DE', 'BO');
insert into iso3166_1 values('BONAIRE, SINT EUSTATIUS AND SABA', 'BONAIRE, SAINT-EUSTACHE ET SABA', 'BQ');
insert into iso3166_1 values('BOSNIA AND HERZEGOVINA', 'BOSNIE-HERZÉGOVINE', 'BA');
insert into iso3166_1 values('BOTSWANA', 'BOTSWANA', 'BW');
insert into iso3166_1 values('BOUVET ISLAND', 'BOUVET, ÎLE', 'BV');
insert into iso3166_1 values('BRAZIL', 'BRÉSIL', 'BR');
insert into iso3166_1 values('BRITISH INDIAN OCEAN TERRITORY', 'OCÉAN INDIEN, TERRITOIRE BRITANNIQUE DE L''', 'IO');
insert into iso3166_1 values('BRUNEI DARUSSALAM', 'BRUNEI DARUSSALAM', 'BN');
insert into iso3166_1 values('BULGARIA', 'BULGARIE', 'BG');
insert into iso3166_1 values('BURKINA FASO', 'BURKINA FASO', 'BF');
insert into iso3166_1 values('BURUNDI', 'BURUNDI', 'BI');
insert into iso3166_1 values('CAMBODIA', 'CAMBODGE', 'KH');
insert into iso3166_1 values('CAMEROON', 'CAMEROUN', 'CM');
insert into iso3166_1 values('CANADA', 'CANADA', 'CA');
insert into iso3166_1 values('CAPE VERDE', 'CAP-VERT', 'CV');
insert into iso3166_1 values('CAYMAN ISLANDS', 'CAÏMANS, ÎLES', 'KY');
insert into iso3166_1 values('CENTRAL AFRICAN REPUBLIC', 'CENTRAFRICAINE, RÉPUBLIQUE', 'CF');
insert into iso3166_1 values('CHAD', 'TCHAD', 'TD');
insert into iso3166_1 values('CHILE', 'CHILI', 'CL');
insert into iso3166_1 values('CHINA', 'CHINE', 'CN');
insert into iso3166_1 values('CHRISTMAS ISLAND', 'CHRISTMAS, ÎLE', 'CX');
insert into iso3166_1 values('COCOS (KEELING) ISLANDS', 'COCOS (KEELING), ÎLES', 'CC');
insert into iso3166_1 values('COLOMBIA', 'COLOMBIE', 'CO');
insert into iso3166_1 values('COMOROS', 'COMORES', 'KM');
insert into iso3166_1 values('CONGO', 'CONGO', 'CG');
insert into iso3166_1 values('CONGO, THE DEMOCRATIC REPUBLIC OF THE', 'CONGO, LA RÉPUBLIQUE DÉMOCRATIQUE DU', 'CD');
insert into iso3166_1 values('COOK ISLANDS', 'COOK, ÎLES', 'CK');
insert into iso3166_1 values('COSTA RICA', 'COSTA RICA', 'CR');
insert into iso3166_1 values('CÔTE D''IVOIRE', 'CÔTE D''IVOIRE', 'CI');
insert into iso3166_1 values('CROATIA', 'CROATIE', 'HR');
insert into iso3166_1 values('CUBA', 'CUBA', 'CU');
insert into iso3166_1 values('CURAÇAO', 'CURAÇAO', 'CW');
insert into iso3166_1 values('CYPRUS', 'CHYPRE', 'CY');
insert into iso3166_1 values('CZECH REPUBLIC', 'TCHÈQUE, RÉPUBLIQUE', 'CZ');
insert into iso3166_1 values('DENMARK', 'DANEMARK', 'DK');
insert into iso3166_1 values('DJIBOUTI', 'DJIBOUTI', 'DJ');
insert into iso3166_1 values('DOMINICA', 'DOMINIQUE', 'DM');
insert into iso3166_1 values('DOMINICAN REPUBLIC', 'DOMINICAINE, RÉPUBLIQUE', 'DO');
insert into iso3166_1 values('ECUADOR', 'ÉQUATEUR', 'EC');
insert into iso3166_1 values('EGYPT', 'ÉGYPTE', 'EG');
insert into iso3166_1 values('EL SALVADOR', 'EL SALVADOR', 'SV');
insert into iso3166_1 values('EQUATORIAL GUINEA', 'GUINÉE ÉQUATORIALE', 'GQ');
insert into iso3166_1 values('ERITREA', 'ÉRYTHRÉE', 'ER');
insert into iso3166_1 values('ESTONIA', 'ESTONIE', 'EE');
insert into iso3166_1 values('ETHIOPIA', 'ÉTHIOPIE', 'ET');
insert into iso3166_1 values('FALKLAND ISLANDS (MALVINAS)', 'FALKLAND, ÎLES (MALVINAS)', 'FK');
insert into iso3166_1 values('FAROE ISLANDS', 'FÉROÉ, ÎLES', 'FO');
insert into iso3166_1 values('FIJI', 'FIDJI', 'FJ');
insert into iso3166_1 values('FINLAND', 'FINLANDE', 'FI');
insert into iso3166_1 values('FRANCE', 'FRANCE', 'FR');
insert into iso3166_1 values('FRENCH GUIANA', 'GUYANE FRANÇAISE', 'GF');
insert into iso3166_1 values('FRENCH POLYNESIA', 'POLYNÉSIE FRANÇAISE', 'PF');
insert into iso3166_1 values('FRENCH SOUTHERN TERRITORIES', 'TERRES AUSTRALES FRANÇAISES', 'TF');
insert into iso3166_1 values('GABON', 'GABON', 'GA');
insert into iso3166_1 values('GAMBIA', 'GAMBIE', 'GM');
insert into iso3166_1 values('GEORGIA', 'GÉORGIE', 'GE');
insert into iso3166_1 values('GERMANY', 'ALLEMAGNE', 'DE');
insert into iso3166_1 values('GHANA', 'GHANA', 'GH');
insert into iso3166_1 values('GIBRALTAR', 'GIBRALTAR', 'GI');
insert into iso3166_1 values('GREECE', 'GRÈCE', 'GR');
insert into iso3166_1 values('GREENLAND', 'GROENLAND', 'GL');
insert into iso3166_1 values('GRENADA', 'GRENADE', 'GD');
insert into iso3166_1 values('GUADELOUPE', 'GUADELOUPE', 'GP');
insert into iso3166_1 values('GUAM', 'GUAM', 'GU');
insert into iso3166_1 values('GUATEMALA', 'GUATEMALA', 'GT');
insert into iso3166_1 values('GUERNSEY', 'GUERNESEY', 'GG');
insert into iso3166_1 values('GUINEA', 'GUINÉE', 'GN');
insert into iso3166_1 values('GUINEA-BISSAU', 'GUINÉE-BISSAU', 'GW');
insert into iso3166_1 values('GUYANA', 'GUYANA', 'GY');
insert into iso3166_1 values('HAITI', 'HAÏTI', 'HT');
insert into iso3166_1 values('HEARD ISLAND AND MCDONALD ISLANDS', 'HEARD-ET-ÎLES MACDONALD, ÎLE', 'HM');
insert into iso3166_1 values('HOLY SEE (VATICAN CITY STATE)', 'SAINT-SIÈGE (ÉTAT DE LA CITÉ DU VATICAN)', 'VA');
insert into iso3166_1 values('HONDURAS', 'HONDURAS', 'HN');
insert into iso3166_1 values('HONG KONG', 'HONG KONG', 'HK');
insert into iso3166_1 values('HUNGARY', 'HONGRIE', 'HU');
insert into iso3166_1 values('ICELAND', 'ISLANDE', 'IS');
insert into iso3166_1 values('INDIA', 'INDE', 'IN');
insert into iso3166_1 values('INDONESIA', 'INDONÉSIE', 'ID');
insert into iso3166_1 values('IRAN, ISLAMIC REPUBLIC OF', 'IRAN, RÉPUBLIQUE ISLAMIQUE D''', 'IR');
insert into iso3166_1 values('IRAQ', 'IRAQ', 'IQ');
insert into iso3166_1 values('IRELAND', 'IRLANDE', 'IE');
insert into iso3166_1 values('ISLE OF MAN', 'ÎLE DE MAN', 'IM');
insert into iso3166_1 values('ISRAEL', 'ISRAËL', 'IL');
insert into iso3166_1 values('ITALY', 'ITALIE', 'IT');
insert into iso3166_1 values('JAMAICA', 'JAMAÏQUE', 'JM');
insert into iso3166_1 values('JAPAN', 'JAPON', 'JP');
insert into iso3166_1 values('JERSEY', 'JERSEY', 'JE');
insert into iso3166_1 values('JORDAN', 'JORDANIE', 'JO');
insert into iso3166_1 values('KAZAKHSTAN', 'KAZAKHSTAN', 'KZ');
insert into iso3166_1 values('KENYA', 'KENYA', 'KE');
insert into iso3166_1 values('KIRIBATI', 'KIRIBATI', 'KI');
insert into iso3166_1 values('KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF', 'CORÉE, RÉPUBLIQUE POPULAIRE DÉMOCRATIQUE DE', 'KP');
insert into iso3166_1 values('KOREA, REPUBLIC OF', 'CORÉE, RÉPUBLIQUE DE', 'KR');
insert into iso3166_1 values('KUWAIT', 'KOWEÏT', 'KW');
insert into iso3166_1 values('KYRGYZSTAN', 'KIRGHIZISTAN', 'KG');
insert into iso3166_1 values('LAO PEOPLE''S DEMOCRATIC REPUBLIC', 'LAO, RÉPUBLIQUE DÉMOCRATIQUE POPULAIRE', 'LA');
insert into iso3166_1 values('LATVIA', 'LETTONIE', 'LV');
insert into iso3166_1 values('LEBANON', 'LIBAN', 'LB');
insert into iso3166_1 values('LESOTHO', 'LESOTHO', 'LS');
insert into iso3166_1 values('LIBERIA', 'LIBÉRIA', 'LR');
insert into iso3166_1 values('LIBYA', 'LIBYE', 'LY');
insert into iso3166_1 values('LIECHTENSTEIN', 'LIECHTENSTEIN', 'LI');
insert into iso3166_1 values('LITHUANIA', 'LITUANIE', 'LT');
insert into iso3166_1 values('LUXEMBOURG', 'LUXEMBOURG', 'LU');
insert into iso3166_1 values('MACAO', 'MACAO', 'MO');
insert into iso3166_1 values('MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', 'MACÉDOINE, L''EX-RÉPUBLIQUE YOUGOSLAVE DE', 'MK');
insert into iso3166_1 values('MADAGASCAR', 'MADAGASCAR', 'MG');
insert into iso3166_1 values('MALAWI', 'MALAWI', 'MW');
insert into iso3166_1 values('MALAYSIA', 'MALAISIE', 'MY');
insert into iso3166_1 values('MALDIVES', 'MALDIVES', 'MV');
insert into iso3166_1 values('MALI', 'MALI', 'ML');
insert into iso3166_1 values('MALTA', 'MALTE', 'MT');
insert into iso3166_1 values('MARSHALL ISLANDS', 'MARSHALL, ÎLES', 'MH');
insert into iso3166_1 values('MARTINIQUE', 'MARTINIQUE', 'MQ');
insert into iso3166_1 values('MAURITANIA', 'MAURITANIE', 'MR');
insert into iso3166_1 values('MAURITIUS', 'MAURICE', 'MU');
insert into iso3166_1 values('MAYOTTE', 'MAYOTTE', 'YT');
insert into iso3166_1 values('MEXICO', 'MEXIQUE', 'MX');
insert into iso3166_1 values('MICRONESIA, FEDERATED STATES OF', 'MICRONÉSIE, ÉTATS FÉDÉRÉS DE', 'FM');
insert into iso3166_1 values('MOLDOVA, REPUBLIC OF', 'MOLDOVA, RÉPUBLIQUE DE', 'MD');
insert into iso3166_1 values('MONACO', 'MONACO', 'MC');
insert into iso3166_1 values('MONGOLIA', 'MONGOLIE', 'MN');
insert into iso3166_1 values('MONTENEGRO', 'MONTÉNÉGRO', 'ME');
insert into iso3166_1 values('MONTSERRAT', 'MONTSERRAT', 'MS');
insert into iso3166_1 values('MOROCCO', 'MAROC', 'MA');
insert into iso3166_1 values('MOZAMBIQUE', 'MOZAMBIQUE', 'MZ');
insert into iso3166_1 values('MYANMAR', 'MYANMAR', 'MM');
insert into iso3166_1 values('NAMIBIA', 'NAMIBIE', 'NA');
insert into iso3166_1 values('NAURU', 'NAURU', 'NR');
insert into iso3166_1 values('NEPAL', 'NÉPAL', 'NP');
insert into iso3166_1 values('NETHERLANDS', 'PAYS-BAS', 'NL');
insert into iso3166_1 values('NEW CALEDONIA', 'NOUVELLE-CALÉDONIE', 'NC');
insert into iso3166_1 values('NEW ZEALAND', 'NOUVELLE-ZÉLANDE', 'NZ');
insert into iso3166_1 values('NICARAGUA', 'NICARAGUA', 'NI');
insert into iso3166_1 values('NIGER', 'NIGER', 'NE');
insert into iso3166_1 values('NIGERIA', 'NIGÉRIA', 'NG');
insert into iso3166_1 values('NIUE', 'NIUÉ', 'NU');
insert into iso3166_1 values('NORFOLK ISLAND', 'NORFOLK, ÎLE', 'NF');
insert into iso3166_1 values('NORTHERN MARIANA ISLANDS', 'MARIANNES DU NORD, ÎLES', 'MP');
insert into iso3166_1 values('NORWAY', 'NORVÈGE', 'NO');
insert into iso3166_1 values('OMAN', 'OMAN', 'OM');
insert into iso3166_1 values('PAKISTAN', 'PAKISTAN', 'PK');
insert into iso3166_1 values('PALAU', 'PALAOS', 'PW');
insert into iso3166_1 values('PALESTINIAN TERRITORY, OCCUPIED', 'PALESTINIEN OCCUPÉ, TERRITOIRE', 'PS');
insert into iso3166_1 values('PANAMA', 'PANAMA', 'PA');
insert into iso3166_1 values('PAPUA NEW GUINEA', 'PAPOUASIE-NOUVELLE-GUINÉE', 'PG');
insert into iso3166_1 values('PARAGUAY', 'PARAGUAY', 'PY');
insert into iso3166_1 values('PERU', 'PÉROU', 'PE');
insert into iso3166_1 values('PHILIPPINES', 'PHILIPPINES', 'PH');
insert into iso3166_1 values('PITCAIRN', 'PITCAIRN', 'PN');
insert into iso3166_1 values('POLAND', 'POLOGNE', 'PL');
insert into iso3166_1 values('PORTUGAL', 'PORTUGAL', 'PT');
insert into iso3166_1 values('PUERTO RICO', 'PORTO RICO', 'PR');
insert into iso3166_1 values('QATAR', 'QATAR', 'QA');
insert into iso3166_1 values('RÉUNION', 'RÉUNION', 'RE');
insert into iso3166_1 values('ROMANIA', 'ROUMANIE', 'RO');
insert into iso3166_1 values('RUSSIAN FEDERATION', 'RUSSIE, FÉDÉRATION DE', 'RU');
insert into iso3166_1 values('RWANDA', 'RWANDA', 'RW');
insert into iso3166_1 values('SAINT BARTHÉLEMY', 'SAINT-BARTHÉLEMY', 'BL');
insert into iso3166_1 values('SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA', 'SAINTE-HÉLÈNE, ASCENSION ET TRISTAN DA CUNHA', 'SH');
insert into iso3166_1 values('SAINT KITTS AND NEVIS', 'SAINT-KITTS-ET-NEVIS', 'KN');
insert into iso3166_1 values('SAINT LUCIA', 'SAINTE-LUCIE', 'LC');
insert into iso3166_1 values('SAINT MARTIN (FRENCH PART)', 'SAINT-MARTIN(PARTIE FRANÇAISE)', 'MF');
insert into iso3166_1 values('SAINT PIERRE AND MIQUELON', 'SAINT-PIERRE-ET-MIQUELON', 'PM');
insert into iso3166_1 values('SAINT VINCENT AND THE GRENADINES', 'SAINT-VINCENT-ET-LES GRENADINES', 'VC');
insert into iso3166_1 values('SAMOA', 'SAMOA', 'WS');
insert into iso3166_1 values('SAN MARINO', 'SAINT-MARIN', 'SM');
insert into iso3166_1 values('SAO TOME AND PRINCIPE', 'SAO TOMÉ-ET-PRINCIPE', 'ST');
insert into iso3166_1 values('SAUDI ARABIA', 'ARABIE SAOUDITE', 'SA');
insert into iso3166_1 values('SENEGAL', 'SÉNÉGAL', 'SN');
insert into iso3166_1 values('SERBIA', 'SERBIE', 'RS');
insert into iso3166_1 values('SEYCHELLES', 'SEYCHELLES', 'SC');
insert into iso3166_1 values('SIERRA LEONE', 'SIERRA LEONE', 'SL');
insert into iso3166_1 values('SINGAPORE', 'SINGAPOUR', 'SG');
insert into iso3166_1 values('SINT MAARTEN (DUTCH PART)', 'SAINT-MARTIN (PARTIE NÉERLANDAISE)', 'SX');
insert into iso3166_1 values('SLOVAKIA', 'SLOVAQUIE', 'SK');
insert into iso3166_1 values('SLOVENIA', 'SLOVÉNIE', 'SI');
insert into iso3166_1 values('SOLOMON ISLANDS', 'SALOMON, ÎLES', 'SB');
insert into iso3166_1 values('SOMALIA', 'SOMALIE', 'SO');
insert into iso3166_1 values('SOUTH AFRICA', 'AFRIQUE DU SUD', 'ZA');
insert into iso3166_1 values('SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', 'GÉORGIE DU SUD-ET-LES ÎLES SANDWICH DU SUD', 'GS');
insert into iso3166_1 values('SOUTH SUDAN', 'SOUDAN DU SUD', 'SS');
insert into iso3166_1 values('SPAIN', 'ESPAGNE', 'ES');
insert into iso3166_1 values('SRI LANKA', 'SRI LANKA', 'LK');
insert into iso3166_1 values('SUDAN', 'SOUDAN', 'SD');
insert into iso3166_1 values('SURINAME', 'SURINAME', 'SR');
insert into iso3166_1 values('SVALBARD AND JAN MAYEN', 'SVALBARD ET ÎLE JAN MAYEN', 'SJ');
insert into iso3166_1 values('SWAZILAND', 'SWAZILAND', 'SZ');
insert into iso3166_1 values('SWEDEN', 'SUÈDE', 'SE');
insert into iso3166_1 values('SWITZERLAND', 'SUISSE', 'CH');
insert into iso3166_1 values('SYRIAN ARAB REPUBLIC', 'SYRIENNE, RÉPUBLIQUE ARABE', 'SY');
insert into iso3166_1 values('TAIWAN, PROVINCE OF CHINA', 'TAÏWAN, PROVINCE DE CHINE', 'TW');
insert into iso3166_1 values('TAJIKISTAN', 'TADJIKISTAN', 'TJ');
insert into iso3166_1 values('TANZANIA, UNITED REPUBLIC OF', 'TANZANIE, RÉPUBLIQUE-UNIE DE', 'TZ');
insert into iso3166_1 values('THAILAND', 'THAÏLANDE', 'TH');
insert into iso3166_1 values('TIMOR-LESTE', 'TIMOR-LESTE', 'TL');
insert into iso3166_1 values('TOGO', 'TOGO', 'TG');
insert into iso3166_1 values('TOKELAU', 'TOKELAU', 'TK');
insert into iso3166_1 values('TONGA', 'TONGA', 'TO');
insert into iso3166_1 values('TRINIDAD AND TOBAGO', 'TRINITÉ-ET-TOBAGO', 'TT');
insert into iso3166_1 values('TUNISIA', 'TUNISIE', 'TN');
insert into iso3166_1 values('TURKEY', 'TURQUIE', 'TR');
insert into iso3166_1 values('TURKMENISTAN', 'TURKMÉNISTAN', 'TM');
insert into iso3166_1 values('TURKS AND CAICOS ISLANDS', 'TURKS-ET-CAÏCOS, ÎLES', 'TC');
insert into iso3166_1 values('TUVALU', 'TUVALU', 'TV');
insert into iso3166_1 values('UGANDA', 'OUGANDA', 'UG');
insert into iso3166_1 values('UKRAINE', 'UKRAINE', 'UA');
insert into iso3166_1 values('UNITED ARAB EMIRATES', 'ÉMIRATS ARABES UNIS', 'AE');
insert into iso3166_1 values('UNITED KINGDOM', 'ROYAUME-UNI', 'GB');
insert into iso3166_1 values('UNITED STATES', 'ÉTATS-UNIS', 'US');
insert into iso3166_1 values('UNITED STATES MINOR OUTLYING ISLANDS', 'ÎLES MINEURES ÉLOIGNÉES DES ÉTATS-UNIS', 'UM');
insert into iso3166_1 values('URUGUAY', 'URUGUAY', 'UY');
insert into iso3166_1 values('UZBEKISTAN', 'OUZBÉKISTAN', 'UZ');
insert into iso3166_1 values('VANUATU', 'VANUATU', 'VU');
insert into iso3166_1 values('VENEZUELA, BOLIVARIAN REPUBLIC OF', 'VENEZUELA, RÉPUBLIQUE BOLIVARIENNE DU', 'VE');
insert into iso3166_1 values('VIET NAM', 'VIET NAM', 'VN');
insert into iso3166_1 values('VIRGIN ISLANDS, BRITISH', 'ÎLES VIERGES BRITANNIQUES', 'VG');
insert into iso3166_1 values('VIRGIN ISLANDS, U.S.', 'ÎLES VIERGES DES ÉTATS-UNIS', 'VI');
insert into iso3166_1 values('WALLIS AND FUTUNA', 'WALLIS ET FUTUNA', 'WF');
insert into iso3166_1 values('WESTERN SAHARA', 'SAHARA OCCIDENTAL', 'EH');
insert into iso3166_1 values('YEMEN', 'YÉMEN', 'YE');
insert into iso3166_1 values('ZAMBIA', 'ZAMBIE', 'ZM');
insert into iso3166_1 values('ZIMBABWE', 'ZIMBABWE', 'ZW');
